import { Inter } from "next/font/google";
<<<<<<< HEAD
import "./globals.css";
=======
import "./buttons.css";
>>>>>>> 785074454b400506bbc5c544123a6e7eb66dacfd

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
